version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: druna_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - druna-net

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: postgres
    volumes:
      - ./configs:/root/configs
    networks:
      - druna-net

volumes:
  pgdata:

networks:
  druna-net:
